# Generated by Django 3.2 on 2024-11-25 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAnitaSol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
