# Generated by Django 3.2 on 2024-11-25 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAnitaSol', '0002_alter_producto_fecha_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
