# Generated by Django 3.2 on 2024-11-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAnitaSol', '0003_alter_venta_fecha_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha_ingreso',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
