# Generated by Django 3.2 on 2024-11-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAnitaSol', '0004_auto_20241125_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaproducto',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
